In [97]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [98]:
import os
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN
import statistics as stat

In [99]:
path1 = '/content/drive/MyDrive/'
dc = os.path.join(path1,'imputated.csv')
diabetes = pd.read_csv(dc)

In [100]:
diabetes = np.array(diabetes)
diabetes

array([['4/21/1991', 1, 8.0, ..., 100.0, 135.0, 119.0],
       ['4/22/1991', 1, 6.333333333, ..., 216.0, 59.0, 211.0],
       ['4/23/1991', 1, 9.0, ..., 257.0, 73.0, 129.0],
       ...,
       ['9/2/1990', 69, nan, ..., 128.5, 114.25, 119.25],
       ['9/3/1990', 69, nan, ..., 128.5, 114.25, 119.25],
       ['9/4/1990', 69, nan, ..., 128.5, 114.25, 119.25]], dtype=object)

In [101]:
min_list = []
for i in range(0,len(diabetes)):
  miin = np.min(diabetes[i][4:7])
  min_list.append(miin)

In [102]:
max_list = []
for i in range(0,len(diabetes)):
  maax = np.max(diabetes[i][4:7])
  max_list.append(maax)

In [103]:
diabetes = pd.DataFrame(diabetes,columns=['date','case','Reg_ins','NPH_ins','Pr_brkfst_glu','Pr_lnch_glu','Pr_sup_glu'])

In [104]:
diabetes.insert(7, column = "min_glu", value = min_list)
diabetes.insert(8, column = "max_glu", value = max_list)
diabetes

,date,case,Reg_ins,NPH_ins,Pr_brkfst_glu,Pr_lnch_glu,Pr_sup_glu,min_glu,max_glu
0,4/21/1991,1,8.0,13.0,100.0,135.0,119.0,100.00,135.0
1,4/22/1991,1,6.333333,13.0,216.0,59.0,211.0,59.00,216.0
2,4/23/1991,1,9.0,13.0,257.0,73.0,129.0,73.00,257.0
3,4/24/1991,1,6.333333,14.0,239.0,41.0,129.0,41.00,239.0
4,4/25/1991,1,5.5,14.0,67.0,100.0,206.0,67.00,206.0
...,...,...,...,...,...,...,...,...,...
3299,8/31/1990,69,NaN,12.0,128.5,114.25,119.25,114.25,128.5
3300,9/1/1990,69,NaN,12.0,128.5,114.25,119.25,114.25,128.5
3301,9/2/1990,69,NaN,12.0,128.5,114.25,119.25,114.25,128.5
3302,9/3/1990,69,NaN,12.0,128.5,114.25,119.25,114.25,128.5
3303,9/4/1990,69,NaN,12.0,128.5,114.25,119.25,114.25,128.5